
package Vista;

import Vista.VistaCategoria;
import Vista.VistaCliente;
import Vista.VistaCompra;
import Vista.VistaConsultasDinamicas;
import Vista.VistaEmpleado;
import Vista.VistaProductos;

import Vista.VistaVentas;

/**
 *
 * @author Maryi 
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        Opciones.addTab("Categorias", new VistaCategoria());
        Opciones.addTab("Productos", new VistaProductos());
        Opciones.addTab("Clientes", new VistaCliente());
        Opciones.addTab("Compras", new VistaCompra());
        Opciones.addTab("Empleados", new VistaEmpleado());
        Opciones.addTab("Ventas", new VistaVentas());
        Opciones.addTab("Consultas con IA", new VistaConsultasDinamicas());
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Opciones = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ferreteria");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                accionCerrarVistaPrincipal(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 939, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accionCerrarVistaPrincipal(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_accionCerrarVistaPrincipal
        // TODO add your handling code here:
        setVisible(false);
        VistaInicioSesion inicioSesion = new VistaInicioSesion();
        inicioSesion.setVisible(true);
    }//GEN-LAST:event_accionCerrarVistaPrincipal


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Opciones;
    // End of variables declaration//GEN-END:variables
}
